FROM nginx:alpine

RUN apk add --no-cache nodejs npm

WORKDIR /app

COPY nginx.dev.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["sh", "-c", "npm install && npm run build -- --watch & nginx -g 'daemon off;'"]
