"""onda 1: sport, court, campos de catalogo em company e user

Revision ID: 0d5b73afd62a
Revises: 12f41c645904
Create Date: 2026-07-18 02:13:42.672144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0d5b73afd62a'
down_revision: Union[str, None] = '12f41c645904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('court',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('photos', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('base_price_hour', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('court_sport',
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['court.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.PrimaryKeyConstraint('court_id', 'sport_id')
    )
    op.add_column('company', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('company', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('company', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('company', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('company', sa.Column('photos', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('company', sa.Column('amenities', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('company', sa.Column('opening_hours', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('sports_of_interest', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('user', sa.Column('favorite_courts', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('user', sa.Column('skill_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'skill_level')
    op.drop_column('user', 'favorite_courts')
    op.drop_column('user', 'sports_of_interest')
    op.drop_column('user', 'longitude')
    op.drop_column('user', 'latitude')
    op.drop_column('user', 'phone')
    op.drop_column('company', 'opening_hours')
    op.drop_column('company', 'amenities')
    op.drop_column('company', 'photos')
    op.drop_column('company', 'longitude')
    op.drop_column('company', 'latitude')
    op.drop_column('company', 'phone')
    op.drop_column('company', 'description')
    op.drop_table('court_sport')
    op.drop_table('court')
    op.drop_table('sport')
    # ### end Alembic commands ###
