from enum import Enum


class ErrorCode(str, Enum):

    # Generic
    CONFLICT = "CONFLICT"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    NOT_FOUND = "NOT_FOUND"
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
    UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY"

    # Auth / Security
    FORBIDDEN = "FORBIDDEN"
    EXPIRED_TOKEN = "EXPIRED_TOKEN"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_TOKEN = "INVALID_TOKEN"
    UNAUTHORIZED = "UNAUTHORIZED"
    RESOURCE_NOT_OWNED = "RESOURCE_NOT_OWNED"

    # User / Company
    WRONG_PASSWORD_PATTERN = "WRONG_PASSWORD_PATTERN"
    NEW_AND_OLD_PASSWORD_ARE_THE_SAME = "NEW_AND_OLD_PASSWORD_ARE_THE_SAME"
    WRONG_PASSWORD = "WRONG_PASSWORD"
    TOKEN_ALREADY_USED = "TOKEN_ALREADY_USED"
    EMAIL_IN_USE = "EMAIL_IN_USE"
    CPF_IN_USE = "CPF_IN_USE"
    CNPJ_IN_USE = "CNPJ_IN_USE"

    # Validation / Input
    INVALID_CODE = "INVALID_CODE"
    INVALID_DATE = "INVALID_DATE"
    INVALID_OFFSET = "INVALID_OFFSET"
    INVALID_ORDERING = "INVALID_ORDERING"
    INVALID_ORDERING_FIELD = "INVALID_ORDERING_FIELD"
    INVALID_PARAMETER = "INVALID_PARAMETER"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"

    # Routing / Infra
    ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND"
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"
