from enum import Enum


class ErrorCode(str, Enum):

    # Generic
    CONFLICT = "CONFLICT"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    NOT_FOUND = "NOT_FOUND"
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
    UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY"

    # Auth / Security
    FORBIDDEN = "FORBIDDEN"
    EXPIRED_TOKEN = "EXPIRED_TOKEN"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_TOKEN = "INVALID_TOKEN"
    UNAUTHORIZED = "UNAUTHORIZED"
    RESOURCE_NOT_OWNED = "RESOURCE_NOT_OWNED"

    # User / Company
    WRONG_PASSWORD_PATTERN = "WRONG_PASSWORD_PATTERN"
    NEW_AND_OLD_PASSWORD_ARE_THE_SAME = "NEW_AND_OLD_PASSWORD_ARE_THE_SAME"
    WRONG_PASSWORD = "WRONG_PASSWORD"
    TOKEN_ALREADY_USED = "TOKEN_ALREADY_USED"
    EMAIL_IN_USE = "EMAIL_IN_USE"
    CPF_IN_USE = "CPF_IN_USE"
    CNPJ_IN_USE = "CNPJ_IN_USE"

    # Validation / Input
    INVALID_CODE = "INVALID_CODE"
    INVALID_DATE = "INVALID_DATE"
    INVALID_OFFSET = "INVALID_OFFSET"
    INVALID_ORDERING = "INVALID_ORDERING"
    INVALID_ORDERING_FIELD = "INVALID_ORDERING_FIELD"
    INVALID_PARAMETER = "INVALID_PARAMETER"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"

    # Routing / Infra
    ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND"
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"

    # Booking / Availability (Fase B)
    SLOT_UNAVAILABLE = "SLOT_UNAVAILABLE"
    INVALID_STATE = "INVALID_STATE"
    INVALID_TIME_RANGE = "INVALID_TIME_RANGE"
    OUTSIDE_OPENING_HOURS = "OUTSIDE_OPENING_HOURS"
    BOOKING_NOT_REFUNDABLE = "BOOKING_NOT_REFUNDABLE"

    # Payment (Fase B)
    PAYMENT_ALREADY_RESOLVED = "PAYMENT_ALREADY_RESOLVED"

    # Groups (Fase C)
    GROUP_FULL = "GROUP_FULL"
    ALREADY_MEMBER = "ALREADY_MEMBER"
    NOT_GROUP_MEMBER = "NOT_GROUP_MEMBER"
    CAPACITY_EXCEEDED = "CAPACITY_EXCEEDED"
    INVALID_GROUP_CONFIG = "INVALID_GROUP_CONFIG"

    # Reviews (Fase F)
    ALREADY_REVIEWED = "ALREADY_REVIEWED"
    BOOKING_NOT_ELIGIBLE_FOR_REVIEW = "BOOKING_NOT_ELIGIBLE_FOR_REVIEW"
